### ISSUE TITLE
Displaying keys in different modes

### ISSUE THREAD

**Issue by SanRider** [Cidan/BetterBags#229]
### Addon Version

v0.1.8

### World of Warcraft Version

Wrath

### Describe the bug

After switching between modes, the keys began to appear behind the bag, also they cannot be used in SectionGrid mode, + the bag with keys is not displayed in SectionGrid mode

### Steps to reproduce

1. Enable OneBag mode
2. Enable SectionGrid mode
3. Drag the window with the bag to any other part of the screen

**Comment by Cidan** [comment]
Can you test using the latest alpha release? I believe this is fixed.

**Comment by SanRider** [comment]
> Can you test using the latest alpha release? I believe this is fixed.

I downloaded the entire repository from git, the addon apparently does not turn on, the interface is not displayed, it is not in the addons tab in the settings, but it is simply in the addons in the menu and on the character selection screen

**Comment by Cidan** [comment]
Sorry, I should have been clear -- you can get the Alpha on Curse/Wago/etc. If you're using the curse client, go to the "Versions" tab when you're looking at the addon page in the client.

**Comment by SanRider** [comment]
The bug is still there 
v.0.1.9
I installed the latest one, now I’ll try all alpha versions up to 0.1.9

**Comment by SanRider** [comment]
0.1.8-1 - The bug is still there
0.1.8-2 - The bug is still there
0.1.8-3 - The bug is still there
0.1.8-4 - The bug is still there
