### ISSUE TITLE
List of items in Custom Category not visible

### ISSUE THREAD

**Issue by tnwn** [Cidan/BetterBags#433]
### Addon Version

v0.1.64

### World of Warcraft Version

Retail Beta

### Describe the bug

When opening the Custom Category section and selecting one previously created Category that has a previously added item to it, the list of items is gone. No new items can be added, and the one already there can't be deleted.

### Steps to reproduce

1. /bb to open options
2. Custom Categories -> Create Category -> New Category Name
3. Name it TEST and click Okay
4. Click TEST in the left list of Custom Categories
5. Drag an item from bag to the right section that says "Drag an item here..."
6. The item is added to the Category but the list of items added that should now be visible on the right side is not there, just an empty field.
![image](https://github.com/Cidan/BetterBags/assets/83972012/0c693bba-de60-4800-99f4-8b9a560f9ab1)

**Comment by Cidan** [comment]
Thanks, I'm able to replicate this. I'll have this fixed in the next update.

**Comment by Cidan** [comment]
After some testing, it seems to happen if you make two categories with the same text string, but in different case. I'll add a guard to stop this from happening.

**Comment by Cidan** [comment]
Hm alright, let me see if I can reproduce this a bit more consistently.

**Comment by tnwn** [comment]
After updating to v0.1.69 today I still have the same issue remaining, also there is this LUA error:
2x BetterBags/data/items.lua:833: attempt to call global 'GetDetailedItemLevelInfo' (a nil value)
[string "@BetterBags/data/items.lua"]:833: in function `AttachBasicItemInfo'
[string "@BetterBags/data/items.lua"]:498: in function <BetterBags/data/items.lua:493>
[string "=[C]"]: in function `xpcall'
[string "@Blizzard_ObjectAPI/Mainline/ContinuableContainer.lua"]:83: in function <...Blizzard_ObjectAPI/Mainline/ContinuableContainer.lua:75>
[string "=(tail call)"]: ?
[string "@BetterBags/data/items.lua"]:493: in function `GetItemData'
[string "@BetterBags/config/itemlist.lua"]:107: in function `SetList'
[string "@BetterBags/config/itemlist.lua"]:76: in function <BetterBags/config/itemlist.lua:69>

Locals:
self = <table> {
 modules = <table> {
 }
 baseName = "BetterBags"
 defaultModuleState = true
 _firstLoad = <table> {
 }
 enabledState = true
 previousItemGUID = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 loadCount = 6
 name = "BetterBags_Items"
 loaders = <table> {
 }
 _doingRefresh = false
 _preSort = false
 _newItemTimers = <table> {
 }
 slotInfo = <table> {
 }
 orderedModules = <table> {
 }
 moduleName = "Items"
}
itemID = 193733
data = <table> {
}
(*temporary) = nil
(*temporary) = 193733
(*temporary) = "attempt to call global 'GetDetailedItemLevelInfo' (a nil value)"
